# Generated by Django 5.1 on 2024-09-11 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0004_customuser_is_buyer_customuser_is_farmer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_buyer',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_farmer',
        ),
    ]
