# Generated by Django 5.1 on 2024-09-11 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0005_remove_customuser_is_buyer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buyer',
            old_name='location',
            new_name='buyer_name',
        ),
        migrations.AddField(
            model_name='buyer',
            name='email',
            field=models.EmailField(default='unknown', max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='buyer',
            name='phone_number',
            field=models.CharField(default='unknown', max_length=15),
        ),
    ]
