# Generated by Django 5.1 on 2024-09-25 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0011_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='produce',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='produce_images/'),
        ),
    ]
